# Generated by Django 3.2.5 on 2021-09-15 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answercomment',
            options={'ordering': ('created',)},
        ),
    ]
