# Generated by Django 3.2.5 on 2021-11-03 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_comment', to='comments.comment'),
        ),
    ]
