# Generated by Django 3.2.5 on 2021-07-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_learningpath_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpath',
            name='icon',
            field=models.ImageField(upload_to='courses/media/icons'),
        ),
    ]
