# Generated by Django 3.2.5 on 2021-07-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_file',
        ),
    ]
