# Generated by Django 3.2.5 on 2021-07-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_lesson_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='attached_files',
            field=models.FileField(blank=True, upload_to='files/lessons'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='media/icons'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, upload_to='media/videos'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='icon',
            field=models.ImageField(blank=True, upload_to='media/icons'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_path',
            field=models.URLField(blank=True),
        ),
    ]
