# Generated by Django 3.2.5 on 2021-07-30 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20210730_2030'),
    ]

    operations = [
    ]
