# Generated by Django 3.2.5 on 2021-08-01 14:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpath',
            name='icon',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
