# Generated by Django 3.2.5 on 2021-08-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_learningpath_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpath',
            name='icon',
            field=models.ImageField(blank=True, upload_to='media/icons'),
        ),
    ]
