# Generated by Django 3.2.5 on 2021-10-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_path',
            field=models.FileField(blank=True, upload_to='media/lessons/videos'),
        ),
    ]
