# Generated by Django 3.2.5 on 2021-11-05 12:20

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20211103_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_path',
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Course Thumbnail'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='next_lesson',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='course',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Course Icon'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Path Icon'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Path Thumbnail'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='attached_files',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Attached files (.zip)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Thumbnail'),
        ),
    ]
