# Generated by Django 3.2.5 on 2021-11-05 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20211105_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='next_lesson',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='courses.lesson'),
        ),
    ]
