# Generated by Django 3.2.5 on 2021-11-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_lesson_next_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='next_lesson',
        ),
    ]
